// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// toTime
StringVector toTime(NumericVector prmSeconds);
RcppExport SEXP XCTrackerCpp_toTime(SEXP prmSecondsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type prmSeconds(prmSecondsSEXP);
    rcpp_result_gen = Rcpp::wrap(toTime(prmSeconds));
    return rcpp_result_gen;
END_RCPP
}
// gradeToInt
IntegerVector gradeToInt(StringVector grades);
RcppExport SEXP XCTrackerCpp_gradeToInt(SEXP gradesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type grades(gradesSEXP);
    rcpp_result_gen = Rcpp::wrap(gradeToInt(grades));
    return rcpp_result_gen;
END_RCPP
}
// inSeconds
NumericVector inSeconds(StringVector raceTimes);
RcppExport SEXP XCTrackerCpp_inSeconds(SEXP raceTimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type raceTimes(raceTimesSEXP);
    rcpp_result_gen = Rcpp::wrap(inSeconds(raceTimes));
    return rcpp_result_gen;
END_RCPP
}
// milePace
StringVector milePace(StringVector raceTime, double distance);
RcppExport SEXP XCTrackerCpp_milePace(SEXP raceTimeSEXP, SEXP distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type raceTime(raceTimeSEXP);
    Rcpp::traits::input_parameter< double >::type distance(distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(milePace(raceTime, distance));
    return rcpp_result_gen;
END_RCPP
}
// timeDifference
StringVector timeDifference(CharacterVector lowerTime, CharacterVector higherTime);
RcppExport SEXP XCTrackerCpp_timeDifference(SEXP lowerTimeSEXP, SEXP higherTimeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type lowerTime(lowerTimeSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type higherTime(higherTimeSEXP);
    rcpp_result_gen = Rcpp::wrap(timeDifference(lowerTime, higherTime));
    return rcpp_result_gen;
END_RCPP
}
// sumOfFive
int sumOfFive(IntegerVector places);
RcppExport SEXP XCTrackerCpp_sumOfFive(SEXP placesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type places(placesSEXP);
    rcpp_result_gen = Rcpp::wrap(sumOfFive(places));
    return rcpp_result_gen;
END_RCPP
}
// placeDot
std::string placeDot(std::string word);
RcppExport SEXP XCTrackerCpp_placeDot(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(placeDot(word));
    return rcpp_result_gen;
END_RCPP
}
// placeDotC
std::string placeDotC(std::string word);
RcppExport SEXP XCTrackerCpp_placeDotC(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(placeDotC(word));
    return rcpp_result_gen;
END_RCPP
}
// scoreDot
std::string scoreDot(std::string word);
RcppExport SEXP XCTrackerCpp_scoreDot(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(scoreDot(word));
    return rcpp_result_gen;
END_RCPP
}
// scoreDotC
std::string scoreDotC(std::string word);
RcppExport SEXP XCTrackerCpp_scoreDotC(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(scoreDotC(word));
    return rcpp_result_gen;
END_RCPP
}
// timeDot
std::string timeDot(std::string word);
RcppExport SEXP XCTrackerCpp_timeDot(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(timeDot(word));
    return rcpp_result_gen;
END_RCPP
}
// timeDotC
std::string timeDotC(std::string word);
RcppExport SEXP XCTrackerCpp_timeDotC(SEXP wordSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type word(wordSEXP);
    rcpp_result_gen = Rcpp::wrap(timeDotC(word));
    return rcpp_result_gen;
END_RCPP
}
// convertPAMS
void convertPAMS(StringVector lines, List dfResults);
RcppExport SEXP XCTrackerCpp_convertPAMS(SEXP linesSEXP, SEXP dfResultsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< List >::type dfResults(dfResultsSEXP);
    convertPAMS(lines, dfResults);
    return R_NilValue;
END_RCPP
}
// removeDistrictNumber
void removeDistrictNumber(StringVector schoolNames);
RcppExport SEXP XCTrackerCpp_removeDistrictNumber(SEXP schoolNamesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type schoolNames(schoolNamesSEXP);
    removeDistrictNumber(schoolNames);
    return R_NilValue;
END_RCPP
}
// convertRH
void convertRH(StringVector lines, List dfResults, bool hasRaceNumbers);
RcppExport SEXP XCTrackerCpp_convertRH(SEXP linesSEXP, SEXP dfResultsSEXP, SEXP hasRaceNumbersSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type lines(linesSEXP);
    Rcpp::traits::input_parameter< List >::type dfResults(dfResultsSEXP);
    Rcpp::traits::input_parameter< bool >::type hasRaceNumbers(hasRaceNumbersSEXP);
    convertRH(lines, dfResults, hasRaceNumbers);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"XCTrackerCpp_toTime", (DL_FUNC) &XCTrackerCpp_toTime, 1},
    {"XCTrackerCpp_gradeToInt", (DL_FUNC) &XCTrackerCpp_gradeToInt, 1},
    {"XCTrackerCpp_inSeconds", (DL_FUNC) &XCTrackerCpp_inSeconds, 1},
    {"XCTrackerCpp_milePace", (DL_FUNC) &XCTrackerCpp_milePace, 2},
    {"XCTrackerCpp_timeDifference", (DL_FUNC) &XCTrackerCpp_timeDifference, 2},
    {"XCTrackerCpp_sumOfFive", (DL_FUNC) &XCTrackerCpp_sumOfFive, 1},
    {"XCTrackerCpp_placeDot", (DL_FUNC) &XCTrackerCpp_placeDot, 1},
    {"XCTrackerCpp_placeDotC", (DL_FUNC) &XCTrackerCpp_placeDotC, 1},
    {"XCTrackerCpp_scoreDot", (DL_FUNC) &XCTrackerCpp_scoreDot, 1},
    {"XCTrackerCpp_scoreDotC", (DL_FUNC) &XCTrackerCpp_scoreDotC, 1},
    {"XCTrackerCpp_timeDot", (DL_FUNC) &XCTrackerCpp_timeDot, 1},
    {"XCTrackerCpp_timeDotC", (DL_FUNC) &XCTrackerCpp_timeDotC, 1},
    {"XCTrackerCpp_convertPAMS", (DL_FUNC) &XCTrackerCpp_convertPAMS, 2},
    {"XCTrackerCpp_removeDistrictNumber", (DL_FUNC) &XCTrackerCpp_removeDistrictNumber, 1},
    {"XCTrackerCpp_convertRH", (DL_FUNC) &XCTrackerCpp_convertRH, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_XCTrackerCpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
