# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Converts seconds to a formatted time, such as "16:26" (Vectorized).
#'
#' @param prmSeconds The amount of seconds to convert.
#' @return The value of prmSeconds in minutes and seconds.
#' @export
#' @useDynLib XCTrackerCpp4
#' @importFrom Rcpp evalCpp
toTime <- function(prmSeconds) {
    .Call('XCTrackerCpp4_toTime', PACKAGE = 'XCTrackerCpp4', prmSeconds)
}

#' Converts year abbreviations ("Sr", etc)to a grade number (12) (Vectorized).
#'
#' @param grades The grade abbreviations to convert
#' @return Integer(s) for each grade.
#' @export
gradeToInt <- function(grades) {
    .Call('XCTrackerCpp4_gradeToInt', PACKAGE = 'XCTrackerCpp4', grades)
}

#' Converts a formatted time to its value in seconds (Vectorized).
#'
#' @param raceTimes The formatted times (ex: "16:26") to convert
#' @return The seconds value for each time
#' @export
inSeconds <- function(raceTimes) {
    .Call('XCTrackerCpp4_inSeconds', PACKAGE = 'XCTrackerCpp4', raceTimes)
}

#' Calculates the milepace  (Vectorized).
#'
#' @param raceTime The formatted times (ex: "16:26") to convert.
#' @param distance The single race distance (default 3.1 miles).
#' @return A formatted string of each milepace.
#' @export
milePace <- function(raceTime, distance = 3.1) {
    .Call('XCTrackerCpp4_milePace', PACKAGE = 'XCTrackerCpp4', raceTime, distance)
}

#' Calculates and formats the difference between two times.
#'
#' @param lowerTime The shorter time.
#' @param higherTime The longer time.
#' @return A formatted string of the difference between the two times.
#' @export
timeDifference <- function(lowerTime, higherTime) {
    .Call('XCTrackerCpp4_timeDifference', PACKAGE = 'XCTrackerCpp4', lowerTime, higherTime)
}

#' Sums the first 5 elements of the vector.
#'
#' @param places A vector to sum.
#' @return The sum of the first 5 elements or -1 if less than 5 are present.
#' @export
sumOfFive <- function(places) {
    .Call('XCTrackerCpp4_sumOfFive', PACKAGE = 'XCTrackerCpp4', places)
}

#' Appends word to the prefix "Place."
#'
#' @param word A string of the word to append
#' @return The concatenation of "Place." and word.
#' @export
placeDot <- function(word) {
    .Call('XCTrackerCpp4_placeDot', PACKAGE = 'XCTrackerCpp4', word)
}

#' Appends the first character of word to the prefix "Place."
#'
#' @param word A string of which the first character will be used.
#' @return The concatenation of "Place." and word's first character.
#' @export
placeDotC <- function(word) {
    .Call('XCTrackerCpp4_placeDotC', PACKAGE = 'XCTrackerCpp4', word)
}

#' Appends word to the prefix "Score."
#'
#' @param word A string of the word to append
#' @return The concatenation of "Score." and word.
#' @export
scoreDot <- function(word) {
    .Call('XCTrackerCpp4_scoreDot', PACKAGE = 'XCTrackerCpp4', word)
}

#' Appends the first character of word to the prefix "Score."
#'
#' @param word A string of which the first character will be used.
#' @return The concatenation of "Score." and word's first character.
#' @export
scoreDotC <- function(word) {
    .Call('XCTrackerCpp4_scoreDotC', PACKAGE = 'XCTrackerCpp4', word)
}

#' Appends word to the prefix "Time."
#'
#' @param word A string of the word to append
#' @return The concatenation of "Time." and word.
#' @export
timeDot <- function(word) {
    .Call('XCTrackerCpp4_timeDot', PACKAGE = 'XCTrackerCpp4', word)
}

#' Appends the first character of word to the prefix "Time."
#'
#' @param word A string of which the first character will be used.
#' @return The concatenation of "Time." and word's first character.
#' @export
timeDotC <- function(word) {
    .Call('XCTrackerCpp4_timeDotC', PACKAGE = 'XCTrackerCpp4', word)
}

#' Modifies the vector to remove any parenthesis numbers (eg "(3)").
#'
#' @param schoolNames The strings to removes numbers from.
#' @export
removeDistrictNumber <- function(schoolNames) {
    invisible(.Call('XCTrackerCpp4_removeDistrictNumber', PACKAGE = 'XCTrackerCpp4', schoolNames))
}

#' Interprets text and stores it in a data frame.
#'
#' @param lines The text of the results to convert.
#' @param dfResults A prebuilt data frame to store results into
#' @param hasRaceNumbers TRUE/FALSE the results have race numbers as the first column.
#' @export
convertRH <- function(lines, dfResults, hasRaceNumbers) {
    invisible(.Call('XCTrackerCpp4_convertRH', PACKAGE = 'XCTrackerCpp4', lines, dfResults, hasRaceNumbers))
}

